### ISSUE TITLE
Add a dropbox upload integration for signature image

### ISSUE THREAD

**Issue by pawisoon** [fle/django-jsignature#14]
It would be nice to integrate dropbox upload instead of keeping the images on the server :)

**Comment by SebCorbin** [comment]
The signature data is just plain JSON structure stored as text in the database.

But I think it would be feasible, in your own project, to hook on saving your model and use the `draw_signature()` function to save a file in a `FileField` on the same model using `django-storages` or any other package to upload it to dropbox.
