### ISSUE TITLE
{{ form.media }} placement requirement

### ISSUE THREAD

**Issue by cbirchby** [fle/django-jsignature#26]
It should be noted that the requirement for placement of {{ form.media }} must be added to the end of your template file and not at the beginning as indicated in the docs.  This ensures you JS is loaded after the form.  So, place {{ form.media }} after your form or at the tail end of the template file.  If you do not place it in the correct location, your signature box will not appear.

**Comment by SebCorbin** [comment]
I'm suprised this isn't working for you as `$(document).ready(function() {})` is used and thus the placement of script won't affect the initialisation of the widget.
