### ISSUE TITLE
Warning about deprecation Image.ANTIALIAS

### ISSUE THREAD

**Issue by nachouve** [fle/django-jsignature#32]
Just for the record:

> DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  im.thumbnail((width, height), Image.ANTIALIAS)

**Comment by ab1211212** [comment]
Indeed, ran into this problem today.  Is there a preferred work around?

**Comment by nachouve** [comment]
I've checked that in the Pillow version 10.0.0  django-jsignature is not working anymore  because this error.

But the [vladimir1284's solution](https://github.com/vladimir1284/django-jsignature/commit/c50fcbbc9624d9b0e24b48d7a27be83646f73105) could be applied.

**Comment by ezarowny** [comment]
Any movement here? There seems to be a PR open for this issue at https://github.com/fle/django-jsignature/pull/36.

**Comment by SebCorbin** [comment]
Closed by #36
