### ISSUE TITLE
Touch screen only shows initial contact

### ISSUE THREAD

**Issue by penguinrunner** [fle/django-jsignature#33]
We have django-jsignature installed in a django application and working perfectly. We started playing with using tablets or touchscreen chromebooks to collect signatures with a stylus or finger, but it only shows the inital spot where you tap the screen. It's actually the exact issue I found in the issues on jSignature's repo https://github.com/brinley/jSignature/issues/186

I was curious if anyone had ran into this before, or if there is something I am not doing correctly.

This repo is awesome, thank you!

Edit: Works fine on my android phone using chrome. Chromebook and Windows do not like it. Also tried in "tablet mode" in windows.

**Comment by penguinrunner** [comment]
I was able to get it working using the jSignature.min.noconflict.js proposed in their repo. I see the one included in this repo is from 2012 so it may be worth updating to the newest one from their repo. There may be more to it than that, but it works on our app and is saving fine to the database.

**Comment by Sudhir-suman** [comment]
C:\Users\HI\AppData\Local\Programs\Python\Python37\python.exe: can't open file 'mange.py': [Errno 2] No such file or directory
im not able to run this project pls hlp m

**Comment by SebCorbin** [comment]
> C:\Users\HI\AppData\Local\Programs\Python\Python37\python.exe: can't open file 'mange.py': [Errno 2] No such file or directory im not able to run this project pls hlp m

You made a mistake, it's `manage.py` not `mange.py` and please open a new issue if you need help

**Comment by SebCorbin** [comment]
Closed by https://github.com/fle/django-jsignature/pull/28
