### ISSUE TITLE
Saved signature doesn't contain dots

### ISSUE THREAD

**Issue by alstr** [fle/django-jsignature#35]
While testing this out, I drew a smiley face with a couple of dots for eyes and a mouth.

When drawing the face, it all appeared correctly.

<img width="218" alt="Screenshot 2023-06-06 at 10 12 56" src="https://github.com/fle/django-jsignature/assets/11612438/000f9825-3667-4d52-a797-d9a032b6216e">

When viewing the saved image though, the dots are missing. If I draw bigger dots, it works fine, but it's almost like tiny little dots aren't included in the data when saving.

<img width="188" alt="Screenshot 2023-06-06 at 10 13 15" src="https://github.com/fle/django-jsignature/assets/11612438/eda60ec1-c54e-4427-a3db-34c3d5f19f16">

Of course I don't expect anyone to draw smiley faces, but it's relevant to 'i' and 'j' letters.

**Comment by SebCorbin** [comment]
Fixed by https://github.com/fle/django-jsignature/pull/38, will be released soon
