### ISSUE TITLE
Encryption of stored signatures

### ISSUE THREAD

**Issue by richardbrockie** [fle/django-jsignature#40]
Hi,

My use case for `django-jsignature` stores the signatures together with other identifying information of users of my application.

It occurs to me that applying an encryption coder/decoder when storing signatures in the database would add protection in the event of a data breach. The encryption key could be another setting, eg:

```
JSIGNATURE_ENCRYPTION_KEY = os.environ.get('JSIGNATURE_ENCRYPTION_KEY')
```

Is this a feature you might consider adding?
Thanks!

**Comment by SebCorbin** [comment]
I won't be adding this feature as it's not the purpose of this package, but a solution can be easily implemented using [`django-secured-fields`](https://pypi.org/project/django-secured-fields/) or [`django-fernet-fields`](https://pypi.org/project/django-fernet-fields/) by adding their mixin to the model field `JsignatureField`

**Comment by richardbrockie** [comment]
@SebCorbin Thanks for the reply - I see how to use the packages you mention to add encryption.
