### ISSUE TITLE
No module named 'example_project'

### ISSUE THREAD

**Issue by R3dPuff1n** [fle/django-jsignature#41]
Hi,
I am getting a No module named 'example_project' when trying to migrate (using ./manage.py migrate).
Am I missing something?

**Comment by SebCorbin** [comment]
Yes, `example_project` from the the documentation is purely, as its meaning implies: an example project, so remove any reference to it or replace with your own project name.

**Comment by R3dPuff1n** [comment]
That does explain a lot. I am quite new to programming in general, thank you for the assistance.

**Comment by SebCorbin** [comment]
Enjoy programming!
